### ISSUE TITLE
Fix ToDoListPWA

### ISSUE THREAD

**Issue by AngeloDotNet** [gptucci/BlazorGpt#1]
Non riuscendo ad aprire una PR (errore 403 in fase di push), ho aperto questa issue per segnalare che nella classe **ToDoListLocalRepo.cs** mancando il metodo **SalvaToDoItem**, in fase di compilazione del progetto VS segnala i seguenti errori:

Nella pagina razor EditToDoItem.razor
```
async Task HandleValidSubmit()
{
    await toDoListLocalRepo.SalvaToDoItem(todoitemInEditing); <--- ERRORE

    todoitemInEditing = null;

    Show = false;
    StateHasChanged();
    await CloseEventCallback.InvokeAsync();
}
```

Nella pagina razor Index.razor
```
async Task DeleteToDoItem(ToDoItem toDoItem)
{
    if (!await jsRuntime.InvokeAsync<bool>("confirm", $"Sei sicuro di voler cancellare l'attività '{toDoItem.Titolo}' ?"))
        return;

    toDoItem.Deleted = true;

    await toDoListLocalRepo.SalvaToDoItem(toDoItem); <--- ERRORE
    await RefreshListaToDoItem();
}
```

La parte di codice mancante invece è presente nell'articolo su ASPItalia al seguente indirizzo: https://www.aspitalia.com/articoli/asp.net-core5/blazor/realizzare-pwa-blazor-aspnetcore-p-5.aspx

**Comment by totti240282** [comment]
Si ie lo avevo segnalato anche io tanto tempo fa ma mai ricevuto risposta, ma come hai detto su Aspitalia c'è tutto.

**Comment by gptucci** [comment]
Grazie infinite !!!!
Appena posso verifico e correggo
Per ora Vi ringrazio tantissimo

**Comment by gptucci** [comment]
Grazie ancora
Piccolo errore con cut & paste
